export const ERROR_CODES = {
  // General Error Codes
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  APPLICATION_ERROR: 'APPLICATION_ERROR',
  HTTP_ERROR: 'HTTP_ERROR',

  // User-related Error Codes
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Database Error Codes
  DATABASE_ERROR: 'DATABASE_ERROR',
  CONFLICT: 'CONFLICT',
  RELATED_RESOURCE: 'RELATED_RESOURCE',
  INVALID_INPUT: 'INVALID_INPUT',
  NOT_NULL_VIOLATION: 'NOT_NULL_VIOLATION',
};
